:set nu
" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible
set backspace=indent,eol,start

filetype indent plugin on " Detect file type by format or content
filetype plugin on	" Provides Intelligent Auto-Indenting
syntax on 		" Enables Syntax Highlighting	
" set hidden 		" Hides Buffers, even when unsaved. Complaints if exit without saving.
" Hide the toobar and menubar
" set guioptions-=m
set guioptions-=T
" window for multiple buffers, and/or:
" set confirm
" set autowriteall

" Colorscheme for the GVim 
if &t_Co >= 256 || has("gui_running")  " Terminal supports 256 colors?
	"set guifont=Droid\ Sans\ Mono\ 9
	set guifont=Monaco\ 10
        "set guifont=Inconsolata\ 14
	      colorscheme distinguished 
        "set background=light
        "colorscheme solarized
        set bg=dark 
else
        " Temporary colorscheme for the gnome-terminal
        " colorscheme grb256 
	      colorscheme jellybeans 
        set bg=dark 
endif
let g:solarized_diffmode="high"       
" let g:molokai_original=1

" The PC is fast enough, do syntax highlight syncing from start
autocmd BufEnter * :syntax sync fromstart

call pathogen#infect() 

set wildmenu		" Better Command-Line completion
set wildignore=*.dll,*.o,*.pyc,*.bak,*.exe,*.jpg,*.jpeg,*.png,*.gif,*$py.class,*.class,*.zip,*.sw[op]
"set wildmode=list:full
set showcmd		" Show partial commands in the last line of the screen
set hlsearch		" Highlight search.
set ignorecase 		" Ignore case when searching
set smartcase		" Ignore case when search pattern all lowercase. Case-sensitive otherwise.

"Indentation Settings. Taken from the Hitchhiker's guide to Python.
set scrolloff=3
set title
set ttyfast
"set tabstop=4
"set softtabstop=4
set expandtab 
set shiftround
"set shiftwidth=4
autocmd FileType python set tabstop=4 softtabstop=4 shiftwidth=4
autocmd FileType javascript set tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufNewFile,BufRead *.json setlocal ft=javascript
let javascript_enable_domhtmlcss=1
autocmd FileType html set tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType css set tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType cpp set tabstop=8 softtabstop=8 shiftwidth=8
autocmd FileType c set tabstop=4 softtabstop=4 shiftwidth=4
au FileType make setlocal noexpandtab " Don't expand tabs into spaces when editing makefiles

set confirm		" Dialog asking if you want to save changed files.
"set visualbell		" Use visual bell instead of beeping when doing something wrong
set mouse=a 		" Enable use of the mouse for all modes
set mousemodel=popup
set pastetoggle=<F2>	" Temporarily disables auto indenting and other stuff. Use right before pasting large amount of code.
" This will stop vim from applying it's own indenting features on the paste.

" Change the statusline display to something that looks useful.
" set cmdheight=2
set statusline=[%l,%v\ %P%M]\ %f\ %r%h%w\ (%{&ff})\ %{fugitive#statusline()}      " requires fugitive.
set showcmd

set t_Co=256              " Explicitly tell vim that the terminal supports 256 colors.
set laststatus=2		" Always show the status line
set encoding=utf-8

" Pathogen Plugin manager info
" Pathogen plugin manager activation; https://github.com/tpope/vim-pathogen 
" Extract plugins to ~/.vim/bundle , and they'll be added to the 'runtimepath' automatically.
" Example - cd ~/.vim/bundle/; git clone git://github.com/tpope/vim-fugitive.git installs the fugitive.vim plugin
" Currently installed plugins --------
" Pathogen (Obviously)
" autoload
" NERDTree
" tcomment
" matchit
" CtrlP
" snipMate
" Taglist; lets see how different it is from Tagbar
" Fugitive - git wrapper for vim
" Gundo
"-------------- Some Custom Mappings ---------------------------------
let mapleader = ";" "Changing the default <leader> key from \ to ;

map <C-n> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$', '\.class$', 'pip-log\.txt$', '\.o$']
let NERDTreeShowBookmarks=1 " Display the NERDTree Bookmarks table on vim startup


" gundo
nnoremap <Leader>u :GundoToggle<CR>

"Shortcut for opening Split-Windows
map <leader>o :split
map <leader>e :vsplit

"Quickly open new tabs
map <leader>t :tabnew<CR>

"Easy Split-Window navigation:
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Clearing the search buffer by pressing ,/ (Note - NOT the leader key)
nmap <silent> ,/ :nohlsearch<CR>

" Reopen a file in sudo-mode by pressing w!!
cmap w!! w !sudo tee % >/dev/null

map <leader>b :CtrlPBuffer<CR>
let g:ctrlp_dotfiles = 0 " Don't scan for dotfiles and dotdirs

" Tagbar mappings
" g:tagbar_ctags_bin
nmap <leader>q :TagbarToggle<CR>
" Taglist mappings. 
nmap <leader>w :TlistToggle<CR>

" Clipboard settings
"copy to the clipboardd
vmap <leader>y :<Esc>`>a<CR><Esc>mx`<i<CR><Esc>my'xk$v'y!xclip -selection c<CR>u 

"paste from the clipboard
map <leader>p :set paste<CR>i<CR><CR><Esc>k:.!xclip -o<CR>JxkJx:set nopaste<CR>

" Tabs shortcuts
map <leader>j :tabnext<CR>
map <leader>k :tabprevious<CR>

" Quickly Change Font-Size, since it's something I seem to do a lot.
nmap <leader>1 :set guifont=Monaco\ 13<CR>
nmap <leader>0 :set guifont=Monaco\ 10<CR>

" Execute currently open script
map <leader>e :!%:p<CR>
" and for when command line args are needed!
map <leader>r :!%:p 

"Generate python ctags
map <F11> :!ctags -R -f ./tags `python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`<CR>

" Racket file settings
if has("autocmd")
    au BufReadPost *.rkt,*.rktl set filetype=scheme
endif
